### PR TITLE
model comparison updates, YIBs/DLEM

### PR DESCRIPTION
**Pull request by JWGits**
YIBs/DLEM still need better data assimilation. If you compare YIBs or DLEM in your graphing script make sure to clear your cached files. The caching function now scales before saving in both models.

### CODE REVIEW

**Comment by mamueller** [comment]
Hurra for the tests!
(Hope you didn't have problems making plots)
Untested code changed in the meantime and broke my example

**Comment by JWGits** [comment]
Hi Markus, no your example worked fine when copied into model_comparison_JW.py. I merged upstream changes and ran it again and the JW model comparison also still runs. Do I need to look into anything?

**Comment by mamueller** [comment]
Just found out that unfortunately the tests don't run for 
everybody else 
(who hasn't installed the extra packages) and, worse make 
jon_yib/model_specific_helpers_2.py 
unloadable.
(So it brakes the general tests in TestSymbolic)
I commented out the code because it would force the dependencies on everybody who wants to work with the yibs model.(compare it to another one)
We would have to change the install script and make anybody run it again to allow normal operation (and running TestSymbolic) 
Since the shape file approach only alleviates the problem of the missing mask in  jon/jibs but does not fix our general problem of incompatible masked areas 
I keep these changes commented even in the test branch.

Thus model_specific_helpers_2 for yibs can  at least  be imported and run without python errors and be kept in the loop for all other tests 
but continues to produce the wrong results due to the missing mask.

@Jon
If you want to work with the shapefile  just uncomment the code (should be quick for you but avoids making the extra packages  mandatory.)

**Comment by JWGits** [comment]
Yeah that's fine. If we need to compare yibs we can do it on my
machine/fork. Let me know when your solution for masking works.

**Pull request merged**
